apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demo-gcb-2"
  annotations:
    google.com/cloudbuild-project-slug: 'intern-infra'
    google.com/cloudbuild-repo-name: rey-gdp-intern/demo-gcb-2
    google.com/cloudbuild-location: 'asia-east1'
spec:
  type: service
  owner: group:sre
  lifecycle: experimental